Repository impactasaurus/app, pull requests merged in 2021-01, with the labels that each got.

#577 branding options in org settings
  src/app/apollo/modules/organisation/index.ts
  src/app/components/OrganisationDon/index.tsx
  src/app/containers/Organisation/index.tsx
  src/app/models/organisation.ts
  src/client.tsx
Labels: new feature

#580 Add GitHub Workflow action for building and testing
  .github/workflows/ci.yaml
  config/test/karma.conf.js
Labels: enhancement

#582 Fix deploy command
  .github/workflows/ci.yaml
Labels: bug
