Repository impactasaurus/app, pull requests merged in 2022-08, with the labels that each got.

#754 Replace node-sass library with sass
  package-lock.json
  package.json
Labels: dependencies

#755 Convert ConfirmButton to functional component
  src/app/components/ConfirmButton/index.tsx
Labels: tech debt

#757 Convert BeneficiaryPill into functional component
  src/app/components/BeneficiaryPill/index.tsx
Labels: tech debt

#761 Convert BeneficiaryTags into functional component
  src/app/components/BeneficiaryTags/index.tsx
Labels: tech debt

#759 Convert ActivityFeedEntry into functional component
  src/app/components/ActivityFeedEntry/index.tsx
Labels: tech debt

#760 Convert Hint into functional component
  src/app/components/Hint/index.tsx
Labels: tech debt

#762 Convert Meeting Graph into functional component
  src/app/components/MeetingGraph/index.tsx
Labels: tech debt

#770 Supports deactivating question and questionnaire notes
  src/app/components/Question/index.tsx
  src/app/components/QuestionInline/index.tsx
  src/app/containers/DataEntry/index.tsx
  src/app/containers/Meeting/index.tsx
  src/app/containers/Meeting/state-machine.ts
  src/app/models/outcomeSet.ts
  src/app/models/question.ts
Labels: new feature
